# 配置RabbitMQ
spring:
  rabbitmq:
    host: 192.168.129.135
    port: 5672
    username: admin
    password: 123456
    publisher-confirm-type: correlated
    publisher-returns: true

server:
  port: 9091
