server:
  port: 9527

spring:
  application:
    name: cloud-gateway # 以微服务注册进consul或nacos服务列表内
  cloud:
    consul: # 配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 # 路由的ID（类似mysql主键），没有固定规则但要求唯一
          uri: lb://cloud-payment-service # 微服务的名字
          #          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          predicates:
#            - Path=/pay/gateway/info/**
            - Path=/pay/gateway/get/** # 断言，路径相匹配的进行路由
          # 多久之后能访问
        #            -  After=2024-06-15T23:17:08.307826900+08:00[Asia/Shanghai]



        - id: pay_routh2
          uri: lb://cloud-payment-service # 微服务的名字
          #          uri: http://localhost:8001
          predicates:
            - Path=/pay/gateway/info/**
            # 定义的My自定义断言，这样写会报错、、开启了简写就可以使用这个方法
            - MyRouterPredicateFactory=gold
        #            - name: MyRouterPredicateFactory
        #              args:
        #                userType: gold

        - id: pay_routh3
          uri: lb://cloud-payment-service # 微服务的名字
          predicates:
            - Path=/pay/gateway/filter/**
          #            - Path=/gateway/filter/** # 断言，为了配合PrefixPath测试过了，暂时注释掉/pay
          #            - Path=/XYZ/abc/{segment}
          filters:
            #            - PrefixPath=/pay # http://localhost:9527/pay/gateway/filter # 被拆分为 PrefixPath + Path
            #            - SetPath=/pay/gateway/{segment} #{segment}表示占位符
            #            - RedirectTo=302,https://www.baidu.com/ # 访问http://localhost:9527/pay/gateway/filter 跳转到https://www.baidu.com/

            - AddRequestHeader=X-Request-disney1,disneyValue1
            - AddRequestHeader=X-Request-disney2,disneyValue2
#            - RemoveRequestHeader=sec-fetch-site # 删除请求头sec-fetch-site
#            - SetRequestHeader=sec-fetch-mode, Blue-updateByDisney # 将请求头sec-fetch-mode对象的值修改为Blue-updateByDisney
#            - AddRequestParameter=customerId,9527001 # 新增请求参数Parameter：k,v
#            - RemoveRequestParameter=customerName # 删除URL请求参数customerName，，及时传过来了也是NULL
#            - AddResponseHeader=X-Response-Disney, BlueResponse # 新增请求参数X-Response-Disney并设值为BlueResponse
#            - SetResponseHeader=Date,2099-11-11 # 设置回应头值为2099-11-11
#            - RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除
